# trailingComma: "es5"
# tabWidth: 4
# semi: false
# singleQuote: true
#
# semi: false
# overrides:
#   - files: "*.test.js"
#     options:
#       semi: true
#   - files:
#       - "*.html"
#       - "legacy/**/*.js"
#     options:
#       tabWidth: 4
