#!/usr/bin/env ansible-playbook ubuntu.yml -D --check --ask-become-pass --ask-vault-pass
---
- hosts: localhost
  connection: local
  gather_facts: no
  become: no

  vars:
    group: "{{ user }}"
    home_dir: "/home/{{ user }}"
    python_version: "3.7.6"
    homebrew_prefix: "/home/linuxbrew/.linuxbrew"
    ansible_supported_os: "Ubuntu"
    ansible_supported_os_version: [18]
    cloud_sdk_python: "/usr/bin/python3"

  pre_tasks:
    - block:
        - name: Check if my_vars.yml file exists
          stat:
            path: my_vars.yml
          register: stat_result
        - name: Include my_vars.yml vars file
          include_vars:
            file: my_vars.yml
          when: stat_result.stat.exists
      tags: always

  roles:
    - { role: check-prereqs, tags: ["check-prereqs-role"] }
    - { role: base, tags: ["base-role"] }
    # - { role: ssh, tags: ["ssh-role"] }
    - { role: git, tags: ["git-role"] }
    - { role: python, tags: ["python-role"] }
    - { role: vim, tags: ["vim-role"] }
    - { role: zsh, tags: ["zsh-role"] }
    # - { role: tmux, tags: ["tmux-role"] }
    # - { role: ansible, tags: ["ansible-role"] }
    # - { role: terraform, tags: ["terraform-role"] }
    - { role: k8s, tags: ["k8s-role"] }
    # - { role: aws, tags: ["aws-role"] }
    # - { role: azure, tags: ["azure-role"] }
    # - { role: gcloud, tags: ["gcloud-role"] }
    # - { role: cronjobs, tags: ["cronjobs-role"] }
    # - { role: sec-tools, tags: ["sec-tools-role"] }
    # - { role: extras, tags: ["extras-role"] }
