---
- block:
    - name: irssi | Install irssi
      community.general.homebrew:
        name: irssi
        state: "present"
      when: install_packages | d() | bool
      tags: brew_install

    - name: irssi | Create {{ home_dir }}/.irssi dir
      file:
        path: "{{ home_dir }}/.irssi"
        state: directory
        mode: 0700
        owner: "{{ user }}"
        group: "{{ group }}"

    - name: irssi | Deploy {{ home_dir }}/.irssi/config
      template:
        src: irssi_config.j2
        dest: "{{ home_dir }}/.irssi/config"
        mode: 0640
        owner: "{{ user }}"
        group: "{{ group }}"

  tags: irssi
