---
# https://codefresh-io.github.io/cli/completion/codefresh-completion/
- block:
    - name: codefresh | Tap Codefresh homebrew repo
      community.general.homebrew_tap:
        name: "codefresh-io/cli"
        state: present
      when: install_packages | d() | bool

    - name: codefresh | Install Codefresh CLI
      community.general.homebrew:
        name: "codefresh"
        state: present
      when: install_packages | d() | bool

    - name: codefresh | Deploy {{ home_dir }}/.cfconfig
      template:
        src: "codefresh_cfconfig.j2"
        dest: "{{ home_dir }}/.cfconfig"
        mode: 0600
        owner: "{{ user }}"
        group: "{{ group }}"
  tags: codefresh
