---
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Add wisely, as too many plugins slow down shell startup.
zsh_plugins:
  - aliases
  - alias-finder
  - auto-notify
  - gcloud
  - git-extras
  - fzf-tab
  - jsontools
  - you-should-use
  - terraform
  - transfer
  - web-search
