

" Automatically install Plug if Vim starts without it
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Call the .vimrc.plug file
if filereadable(expand("~/.vimrc.plug"))
    source ~/.vimrc.plug
endif


set runtimepath^=~/.vim/bundle/ctrlp.vim "for usage instructions and configuration details -> :help ctrlp.txt

set encoding=utf-8

set diffopt=filler,context:0 "suppress common lines and only show the diffs

autocmd BufWritePre * %s/\s\+$//e "remove all trailing whitespace

set clipboard=unnamed "copy stuff from vim to OS buffer

au BufRead,BufNewFile */*Ansible/*.yml set filetype=yaml.ansible

" # turn off auto-insert of comments
augroup auto_comment
    au!
    au FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o
augroup END

"
" NERDTree
"
" Map `Ctrl+n` to open NERDTree
map <C-n> :NERDTreeToggle<CR>

" default arrows
"let g:NERDTreeDirArrowExpandable = '▸'
"let g:NERDTreeDirArrowCollapsible = '▾'

" add the proper PEP 8 indentation
au BufNewFile,BufRead *.py set tabstop=4 softtabstop=4 shiftwidth=4 textwidth=79 expandtab autoindent fileformat=unix

" For other full stack development
au BufNewFile,BufRead *.js, *.html, *.css set tabstop=2 softtabstop=2 shiftwidth=2

" YouCompleteMe configs

let g:ycm_autoclose_preview_window_after_completion=1 " ensures that the auto-complete window goes away when you’re done with it
map <leader>g  :YcmCompleter GoToDefinitionElseDeclaration<CR> "defines a shortcut for goto definition

" make your code look pretty after installing syntastic and vim-flake8 plugins
let python_highlight_all=1
syntax on

set spell spelllang=en " (or `en_us`)
set spellfile=~/src/nicolas-g/dotfiles/vimspellen.utf-8.add "  the name of your spellfile must end in .{encoding}.add where {encoding} is the character encoding of the file
