---
- block:
    # There is an issue for this to work in Alacritty with tmux, it is actually a tmux
    # issue. This does work if you are not running tmux in Alacritty.
    # see -> https://github.com/alacritty/alacritty/issues/1549 .

    # pam-reattach required for sudo TouchId to work for tmux
    - name: macos-sudo-touchid | Include brew_install.yml
      import_tasks: "../../../roles/shared/tasks/brew_install.yml"
      vars:
        brew_packages:
          - "pam-reattach"

    - name: macos-sudo-touchid | Enable Touch ID for sudo
      template:
        src: sudo_local.j2
        dest: "/etc/pam.d/sudo_local"
        owner: root
        group: wheel
        mode: "0444"
      become: yes
      become_method: sudo
  tags: macos-sudo-touchid
