---
- block:
    - name: macos-dock | Install dockutil
      community.general.homebrew:
        name: "dockutil"
        state: "present"

    - name: macos-dock | Remove all crap from Dock
      command: "{{ homebrew_prefix }}/bin/dockutil --remove '{{ item }}'"
      ignore_errors: true
      with_items: "{{ dockitems_to_remove }}"

    - name: macos-dock | Check if items in dock exist
      shell: dockutil --find '{{ item.name }}' || dockutil --add '{{ item.path }}'
      with_items: "{{ dockitems_to_persist }}"

    - name: macos-dock | Fix order
      command: dockutil --move '{{ item.name }}' --position {{ item.pos }}
      with_items: "{{ dockitems_to_persist }}"

  tags: macos-dock
