---
- block:
    - name: Include mac-app-store.yml
      include: mac-app-store.yml

    - name: Creates the "locate" database if it doesn't exist
      command:
        cmd: "launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist"
        creates: /var/db/locate.database
      become: yes
      become_method: sudo

    - name: Include macos-defaults.yml
      include: macos-defaults.yml

    - name: Include macos-dock
      include: macos-dock.yml

    - name: Include macos-sudo-touchid
      include: macos-sudo-touchid.yml

    - name: macos | Install noTunes and TopNotch
      community.general.homebrew:
        # noTunes  - Prevents iTunes or Apple Music from launching
        # TopNotch - Makes the notch disappear (see manual steps)
        name: "notunes,topnotch"
        state: "present"
      tags: brew
      when: install_packages | d() | bool

  tags: macos
