---
- block:
    - name: zsh | Install shell related packages
      community.general.homebrew:
        name: "{{ item }}"
        state: "present"
      loop:
        - fzf
        - z
        - zsh
        - zsh-autosuggestions
        - zsh-completions
        - zsh-git-prompt
        - zsh-history-substring-search
        - zsh-lovers
        - zsh-navigation-tools
        - zsh-syntax-highlighting
      tags: brew
      when: install_packages | d() | bool

    # https://github.com/ohmyzsh/ohmyzsh
    - name: zsh | Download oh-my-zsh installer
      get_url:
        url: "https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh"
        dest: "/tmp/oh-my-zsh-install.sh"
        mode: "0750"

    - name: packages | Install oh-my-zsh
      command: "sh /tmp/oh-my-zsh-install.sh"
      args:
        creates: "{{ home_dir }}/.oh-my-zsh"

    - name: zsh | Create {{ home_dir }}/.zshrc.d dir
      file:
        path: "{{ home_dir }}/.zshrc.d"
        state: directory
        mode: 0700
        owner: "{{ user }}"
        group: "{{ group }}"

    - name: zsh | Deploy {{ home_dir }}/.zshrc
      template:
        src: "{{ item }}.j2"
        dest: "{{ home_dir }}/.{{ item }}"
        mode: 0644
        owner: "{{ user }}"
        group: "{{ group }}"
      loop:
        - "zshrc"
        - "zprofile"
      tags: ["zshrc-conf", "conf"]

    - name: zsh | Deploy {{ home_dir }}/.fzf.zsh
      template:
        src: "fzf.zsh.j2"
        dest: "{{ home_dir }}/.fzf.zsh"
        mode: 0644
        owner: "{{ user }}"
        group: "{{ group }}"

    - name: zsh | Clone zsh-completions plugin repo # noqa 401 (Package installs should not use latest)
      git:
        repo: https://github.com/zsh-users/zsh-completions
        dest: "~/.oh-my-zsh/custom/plugins/zsh-completions"
        force: yes

    - name: zsh | Clone zsh-syntax-highlighting plugin repo # noqa 401 (Package installs should not use latest)
      git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: "~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
        force: yes

      # add fzf-tab to your plugin list
    - name: zsh | Clone fzf-tab plugin repo # noqa 401 (Package installs should not use latest)
      git:
        repo: "https://github.com/Aloxaf/fzf-tab"
        dest: "~/.oh-my-zsh/custom/plugins/fzf-tab"
        force: yes

      # add nvm to your plugin list
    - name: zsh | Clone nvm plugin repo # noqa 401 (Package installs should not use latest)
      git:
        repo: "https://github.com/lukechilds/zsh-nvm"
        dest: "~/.oh-my-zsh/custom/plugins/zsh-nvm"
        force: yes

    # Removes Tmux duplicates from PATH
    # https://apple.stackexchange.com/questions/248813/tmux-always-modify-my-zsh-path
    # https://coderwall.com/p/4l16zq/pyenv-inside-tmux-with-zsh-on-a-mac
    - name: zsh | Deploy consolidate-path
      copy:
        src: "consolidate-path.sh"
        dest: /usr/local/bin/consolidate-path
        mode: 0755
        owner: "{{ user }}"
        group: "{{ group }}"
      become: yes
      when: ansible_os_family == 'Darwin'

    - name: zsh | install starship.yml
      include: starship.yml

  tags: zsh
