---
- block:
    - name: aws | Create {{ home_dir }}/.aws dir
      file:
        path: "{{ home_dir }}/.aws"
        state: directory
        mode: 0755
        owner: "{{ user }}"
        group: "{{ group }}"

    - name: aws | Include brew_install.yml
      import_tasks: "../../../roles/shared/tasks/brew_install.yml"
      vars:
        brew_packages:
          - "awscli"
          - "aws-iam-authenticator"
          - "aws-vault" # Supports password-store, Use the --backend flag or AWS_VAULT_BACKEND environment variable to specify.

    - name: aws | Include brew_cask_install.yml
      import_tasks: "../../../roles/shared/tasks/brew_cask_install.yml"
      vars:
        brew_cask_packages:
          - "aws-vpn-client"

    - name: aws | Deploy {{ home_dir }}/.aws/config
      copy:
        src: config
        dest: "{{ home_dir }}/.aws/config"
        mode: 0400
        owner: "{{ user }}"
        group: "{{ group }}"
        backup: True
  when: run_aws | d() | bool
  tags: aws
