---
- block:
    - name: aws | Create {{ home_dir }}/.aws dir
      file:
        path: "{{ home_dir }}/.aws"
        state: directory
        mode: 0755
        owner: "{{ user }}"
        group: "{{ group }}"

    - name: aws | Install awscli
      community.general.homebrew:
        name: "awscli,aws-iam-authenticator,aws-vpn-client"
        state: "present"
      when: install_packages | d() | bool
      tags: brew

    - name: aws | Deploy {{ home_dir }}/.aws/config
      copy:
        src: config
        dest: "{{ home_dir }}/.aws/config"
        mode: 0400
        owner: "{{ user }}"
        group: "{{ group }}"
        backup: True
  when: run_aws | d() | bool
  tags: aws
