---
- block:
    - name: jrnl | brew install jrnl
      community.general.homebrew:
        name: "jrnl"
        state: "present"
      when: install_packages | d() | bool
      tags: brew

    - name: jrnl | Create {{ jrnl_config_dir }} config dir
      file:
        path: "{{ jrnl_config_dir }}"
        state: directory
        mode: 0700
        owner: "{{ user }}"
        group: "{{ group }}"

    - name: jrnl | Deploy {{ jrnl_config_dir }}/jrnl.yaml
      template:
        src: jrnl.yaml.j2
        dest: "{{ jrnl_config_dir }}/jrnl.yaml"
        mode: 0644
        owner: "{{ user }}"
        group: "{{ group }}"

    - name: jrnl | Create {{ home_dir }}/.jrnl data dir
      file:
        path: "{{ jrnl_data_dir }}"
        state: directory
        mode: 0755
        owner: "{{ user }}"
        group: "{{ group }}"
  vars:
    jrnl_data_dir: "{{ home_dir }}/.jrnl"
    jrnl_config_dir: "{{ home_dir }}/.config/jrnl"
  tags: jrnl
