---
- block:
    - name: extras | Include brew_install.yml
      import_tasks: "../../../roles/shared/tasks/brew_install.yml"
      vars:
        brew_packages: "{{ homebrew_extras }}"
    - name: extras | Include brew_cask_install.yml
      import_tasks: "../../../roles/shared/tasks/brew_cask_install.yml"
      vars:
        brew_cask_packages: "{{ homebrew_cask_extras }}"

    - name: extras | Deploy {{ home_dir }}/.aliases.d/extras
      copy:
        src: extras_aliases
        dest: "{{ home_dir }}/.aliases.d/extras"
        mode: 0644
        owner: "{{ user }}"
        group: "{{ group }}"
      tags: ["aliases", "extra-aliases"]

    - name: base | Deploy {{ home_dir }}/.functions.d/extras
      copy:
        src: extras_functions
        dest: "{{ home_dir }}/.functions.d/extras"
        mode: 0644
        owner: "{{ user }}"
        group: "{{ group }}"
      tags: functions

    - name: base | Include pianobar.yml
      include: pianobar.yml

    - name: Include backup.yml
      include: backup.yml

    - name: Include nerd-fonts.yml
      include: nerd-fonts.yml

    - name: Include jrnl.yml
      include: jrnl.yml

    - name: Include speedtest.yml
      include: speedtest.yml

    - name: Include ngrok.yml
      include: ngrok.yml

    - name: Include jira-cli.yml
      include: jira-cli.yml

    - name: Include perfops.yml
      include: perfops.yml

    - name: extras | Deploy /usr/local/bin/scpdot.sh
      copy:
        src: "scpdot.sh"
        dest: "/usr/local/bin/scpdot.sh"
        mode: 0755
      become: yes
      become_method: sudo
  tags: extras
