---
- block:
    - name: pianobar | brew install pianobar
      community.general.homebrew:
        name: "pianobar"
        state: "present"
      when: install_packages | d() | bool
      tags: brew

    - name: pianobar | Create {{ home_dir }}/.config/pianobar dir
      file:
        path: "{{ home_dir }}/.config/pianobar"
        state: directory
        mode: 0755
        owner: "{{ user }}"
        group: "{{ group }}"

    - name: pianobar | Deploy {{ home_dir }}/.config/pianobar/config
      template:
        src: pianobar_connfig.j2
        dest: "{{ home_dir }}/.config/pianobar/config"
        mode: 0644
        owner: "{{ user }}"
        group: "{{ group }}"

  tags: pianobar
