---
- block:
    - name: gcloud | Install gcloud
      community.general.homebrew_cask:
        name: google-cloud-sdk
        state: "present"
      when: install_packages | d() | bool
      tags: brew_cask_install

    - name: gcloud | Create {{ home_dir }}/.config/gcloud directories
      file:
        path: "{{ home_dir }}/.config/{{ item }}"
        state: directory
        mode: 0755
        owner: "{{ user }}"
        group: "{{ group }}"
      loop:
        - "gcloud"
        - "gcloud/configurations"
        - "gcloud/credentials"

    - name: gcloud | Deploy {{ home_dir }}/.aliases.d/gcloud
      copy:
        src: gcloud_aliases
        dest: "{{ home_dir }}/.aliases.d/gcloud"
        mode: 0644
        owner: "{{ user }}"
        group: "{{ group }}"
      tags: ["aliases", "gcloud-aliases"]

    - name: gcloud | Deploy {{ home_dir }}/.config/gcloud/configurations/config_{{ item.project }}
      template:
        src: config.j2
        dest: "{{ home_dir }}/.config/gcloud/configurations/config_{{ item.project }}"
        mode: 0644
        owner: "{{ user }}"
        group: "{{ group }}"
      loop: "{{ gcloud_configs }}"

    - name: gcloud | Install gcloud components
      command: "{{ homebrew_prefix }}/bin/gcloud components install {{ item }}"
      register: cmd_result
      loop:
        - "config-connector"
        - "cloud-build-local"
        - "gke-gcloud-auth-plugin"
        - "gsutil"
        - "nomos"
      changed_when: '"All components are up to date" not in cmd_result.stderr'
  tags: gcloud
