---
- block:
    - name: base | Include brew_install.yml
      import_tasks: "../../../roles/shared/tasks/brew_install.yml"
      vars:
        brew_packages: "{{ homebrew_essentials }}"
      when: ansible_os_family == 'Darwin'

    - name: base | Include brew_cask_install.yml
      import_tasks: "../../../roles/shared/tasks/brew_cask_install.yml"
      vars:
        brew_cask_packages: "{{ homebrew_cask_essentials }}"
      when: ansible_os_family == 'Darwin'

    - name: base | Create /usr/local/bin dir
      file:
        path: "/usr/local/bin"
        state: directory
        mode: 0755
        owner: "{{ user }}"
        group: "{{ group }}"
      become: yes
      when: ansible_os_family == 'Darwin'

    - name: base | Create {{ home_dir }}/.{{ item }} dir
      file:
        path: "{{ home_dir }}/.{{ item }}"
        state: directory
        mode: 0755
        owner: "{{ user }}"
        group: "{{ group }}"
      loop:
        - config
        - aliases.d
        - functions.d

    - name: base | Deploy {{ home_dir }}/.aliases.d/base
      template:
        src: base_aliases.j2
        dest: "{{ home_dir }}/.aliases.d/base"
        mode: 0644
        owner: "{{ user }}"
        group: "{{ group }}"
      tags: ["aliases", "base-aliases"]

    - name: base | Deploy {{ home_dir }}/.functions.d/base
      copy:
        src: base_functions
        dest: "{{ home_dir }}/.functions.d/base"
        mode: 0644
        owner: "{{ user }}"
        group: "{{ group }}"
      tags: functions

    - name: base | Deploy {{ home_dir }}/.env
      template:
        src: env.j2
        dest: "{{ home_dir }}/.env"
        mode: 0644
        owner: "{{ user }}"
        group: "{{ group }}"
      tags: env

    - name: base | Deploy {{ home_dir }}/.bashrc
      copy:
        src: bashrc
        dest: "{{ home_dir }}/.bashrc"
        mode: 0644
        owner: "{{ user }}"
        group: "{{ group }}"
      tags: ["aliases", "base-aliases"]

  tags: base
