---
- block:
    - name: starship | Deploy starship.toml
      copy:
        src: "starship.toml"
        dest: "~/.config/starship.toml"
        mode: 0644
        owner: "{{ user }}"
        group: "{{ group }}"
  tags: starship
