---
- block:
    # required for Vim YouCompleteMe plugin to work on MacOS
    - name: vim | Install brew cmake/macvim
      community.general.homebrew:
        name: "{{ item }}"
        state: "present"
      when: install_packages | d() | bool and ansible_os_family == 'Darwin'
      tags: brew
      loop:
        - "cmake"
        - "macvim"

    - name: vim | Deploy {{ home_dir }}/.{{ item }}
      copy:
        src: "{{ item }}"
        dest: "{{ home_dir }}/.{{ item }}"
        mode: 0644
        owner: "{{ user }}"
        group: "{{ group }}"
      loop:
        - "vimrc"
        - "vimrc.plug"

    - name: vim | Clone zsh-completions plugin repo # noqa 401 (Package installs should not use latest)
      git:
        repo: https://github.com/ctrlpvim/ctrlp.vim
        dest: "{{ home_dir }}/.vim/bundle/ctrlp.vim"
        force: yes

    - name: vim | Install powerline-status
      pip:
        name: powerline-status
      when: install_packages | d() | bool

  tags: vim
