---
- block:
    - name: vim | Install brew macvim/nodejs
      community.general.homebrew:
        name: "{{ item }}"
        state: "present"
      when: install_packages | d() | bool and ansible_os_family == 'Darwin'
      tags: brew
      loop:
        - "neovim"
        - "nodejs" # Required by coc autocomplete

    - name: vim | Deploy {{ home_dir }}/.{{ item }}
      copy:
        src: "{{ item }}"
        dest: "{{ home_dir }}/.{{ item }}"
        mode: 0644
        owner: "{{ user }}"
        group: "{{ group }}"
      loop:
        - "vimrc"
        - "vimrc.plug"

    - name: vim | Clone zsh-completions plugin repo # noqa 401 (Package installs should not use latest)
      git:
        repo: https://github.com/ctrlpvim/ctrlp.vim
        dest: "{{ home_dir }}/.vim/bundle/ctrlp.vim"
        force: yes

    - name: vim | Install powerline-status
      pip:
        name: powerline-status
      when: install_packages | d() | bool

    - name: vim | Deploy {{ home_dir }}/.aliases.d/{{ item }}
      copy:
        src: "vim_aliases"
        dest: "{{ home_dir }}/.aliases.d/vim"
        mode: 0644
        owner: "{{ user }}"
        group: "{{ group }}"
      tags: ["aliases", "vim-aliases"]

    - name: vim | Include lunar_vim.yml
      include: lunar_vim.yml

  tags: vim
