---
- block:
    - name: sec-tools | Install brew cask packages
      community.general.homebrew_cask:
        name: "{{ item }}"
        state: "present"
      loop:
        - 1password-cli
        - 1password
        - authy
        - cryptomator
        - gpg-suite
        - keybase
        - ots # one time secret
        - veracrypt
      tags: brew
      when: install_packages | d() | bool

    - name: sec-tools | Install brew packages
      community.general.homebrew:
        name: "{{ item }}"
        state: "present"
      loop:
        # Aircrack not supported for M1 architecture yet
        # https://github.com/aircrack-ng/aircrack-ng/issues/1957
        # https://github.com/aircrack-ng/aircrack-ng/issues/2214
        # - aircrack-ng
        - pass
        - pass-otp
        - gnupg
        - lastpass-cli
        - mitmproxy
        - netcat
      tags: brew
      when: install_packages | d() | bool

    - name: base | Deploy {{ home_dir }}/.aliases.d/sec_tools
      template:
        src: sec_aliases.j2
        dest: "{{ home_dir }}/.aliases.d/sec_tools"
        mode: 0644
        owner: "{{ user }}"
        group: "{{ group }}"
      tags: aliases
  tags: sec-tools
