---
use_ansible_hard_coded_facts: False
# Since facts gathering can slow down each run and be annoying when you run Ansible multiple
# times, we have hard coded the values here and use them when the var `use_ansible_hard_coded_facts` flag is set to `True`
# To get the current Ansible facts run the bellow command:
#
#   ansible -m setup -a"gather_subset=facter" localhost | egrep "ansible_distribution|ansible_distribution_major_version|ansible_machine|ansible_os_family|ansible_system"
#
ansible_distribution_hard_coded: "MacOSX"
ansible_distribution_major_version_hard_coded: "10"
ansible_machine_hard_coded: "x86_64"
ansible_os_family_hard_coded: "Darwin"
ansible_system_hard_coded: "Darwin"

ansible_supported_os: "MacOSX"
ansible_supported_os_version: [10,11]
run_check_prereqs: True
