---
- block:
    - name: host_files | Deploy update_hostFile.sh scrip
      copy:
        src: "ng_update_hostFile.sh"
        dest: "/usr/local/bin/ng_update_hostFile.sh"
        mode: 0755

    - name: host_files | Deploy My custom BlackHosts file
      copy:
        owner: root
        group: wheel
        src: "myBlackHosts"
        dest: "/etc/myBlackHosts"
        mode: 0644

    - name: host_files | Deploy custom myHosts file
      template:
        owner: root
        group: wheel
        src: "myHosts"
        dest: "/etc/myHosts"
        mode: 0644

    - name: host_files | Backup shell history
      cron:
        name: "Updaste /etc/hosts file"
        special_time: daily
        job: "/usr/local/bin/ng_update_hostFile.sh"

  become: yes
  become_method: sudo
  tags: host_files
