---
- block:
    - name: openvpn | Install brew tunnelblick
      community.general.homebrew_cask:
        name: "tunnelblick"
        state: "present"
      when: install_packages | d() | bool
      tags: brew

    - name: openvpn | Create {{ home_dir }}/.ovpn dir
      file:
        path: "{{ home_dir }}/.ovpn"
        state: directory
        mode: 0700
        owner: "{{ user }}"
        group: "{{ group }}"

    - name: openvpn | Deploy {{ home_dir }}/.ovpn/xspdev/xspdev.conf"
      template:
        src: ovpn.conf.j2
        dest: "{{ home_dir }}/.ovpn/xspdev/xspdev.conf"
        mode: 0600
        owner: "{{ user }}"
        group: "{{ group }}"

  tags: openvpn
